Build working on bitrise

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,65 +1,33 @@
 ---
 format_version: '5'
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
-project_type: other
+project_type: react-native
 trigger_map:
 - push_branch: "*"
-  workflow: primary
+  workflow: release_android
 - pull_request_source_branch: "*"
   workflow: primary
 workflows:
-  primary:
+  release_android:
     steps:
-    - activate-ssh-key:
-        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-    - git-clone@4.0.11: {}
-    - cache-pull@2.0.1: {}
-    - yarn@0.0.7:
+    - install-missing-android-tools: {}
+    - change-android-versioncode-and-versionname@1.1.1:
         inputs:
-        - command: install
-        title: Yarn Instal
-    - cache-push@2.0.5:
+        - build_gradle_path: "$BITRISE_SOURCE_DIR/android/app/build.gradle"
+        - new_version_name: "$BITRISE_BUILD_NUMBER"
+    - android-build@0.9.4:
         inputs:
-        - compress_archive: 'true'
-        - cache_paths: node_modules
-    - script@1.1.5:
-        title: Build Android and iOS
+        - project_location: "$PROJECT_LOCATION"
+        - module: "$MODULE"
+        - variant: "$BUILD_VARIANT"
+    - sign-apk@1.2.2: {}
+    - deploy-to-bitrise-io@1.3.12: {}
+    - create-install-page-qr-code@1.0.0: {}
+    - slack@2.7.3:
         inputs:
-        - content: |-
-            #!/usr/bin/env bash
-            # fail if any commands fails
-            set -e
-            # debug log
-            set -x
-            yarn run build:android
-            #yarn run build:ios
-
-            export ANDROID_APK_URL=./app/build/outputs/apk/app-release-unsigned.apk
-            #export IOS_IPA_URL=`exp build:status | grep 'IPA' | cut -c17-2000`
-            envman add --key ANDROID_APK_URL --value ${ANDROID_APK_URL}
-            #envman add --key IOS_IPA_URL --value ${IOS_IPA_URL}
-    - file-downloader@1.0.1:
-        inputs:
-        - destination: "$BITRISE_APK_PATH"
-        - source: "$ANDROID_APK_URL"
-        title: Download Expo Android APK
-    - file-downloader@1.0.1:
-        inputs:
-        - destination: "$BITRISE_IPA_PATH"
-        - source: "$IOS_IPA_URL"
-        title: Download Expo iOS IPA
-    - deploy-to-bitrise-io@1.3.12:
-        title: Deploy Android APK to Bitrise.io
-        inputs:
-        - deploy_path: "$BITRISE_SIGNED_APK_PATH"
-    - create-install-page-qr-code@1.0.0:
-        title: Create Android install page QR code
-    - slack:
-        inputs:
-        - webhook_url: "$SLACK_WEBHOOK_URL"
-        - channel: "$SLACK_CHANNEL"
-        - message: 'Android - Baixe o aplicativo aqui (v$BITRISE_BUILD_NUMBER): $BITRISE_PUBLIC_INSTALL_PAGE_URL
-            .'
+        - channel: "#musicplayce-bitrise"
+        - webhook_url: https://hooks.slack.com/services/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
+        - message: Android - Baixe o aplicativo aqui (v$BITRISE_BUILD_NUMBER)
         - message_on_error: Android - Erro
         - title_link: "$BITRISE_PUBLIC_INSTALL_PAGE_URL"
         - fields: |-
@@ -72,19 +40,51 @@ workflows:
             View Build|${BITRISE_BUILD_URL}
             View Commit|https://gitlab.com/dev_squad/musicplayce-app/commit/$BITRISE_GIT_COMMIT
             Install Page|${BITRISE_PUBLIC_INSTALL_PAGE_URL}
-        - image_url: "$BITRISE_PUBLIC_INSTALL_PAGE_QR_CODE_IMAGE_URL"
-    - deploy-to-bitrise-io@1.3.12:
-        title: Deploy IOS IPA to Bitrise.io
+    before_run:
+    - release_ios
+  primary:
+    steps:
+    - activate-ssh-key:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone@4.0.11: {}
+    - script@1.1.5:
+        title: Set BUILD_NUMBER Env Var
         inputs:
-        - deploy_path: "$BITRISE_IPA_PATH"
-    - create-install-page-qr-code@1.0.0:
-        title: Create iOS install page QR code
-    - slack:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # write your script here
+            envman add --key BUILD_NUMBER --value $BITRISE_BUILD_NUMBER
+
+            # or run a script from your repository, like:
+            # bash ./path/to/script.sh
+            # not just bash, e.g.:
+            # ruby ./path/to/script.rb
+    - npm@0.9.1:
         inputs:
-        - webhook_url: "$SLACK_WEBHOOK_URL"
-        - channel: "$SLACK_CHANNEL"
-        - message: 'iOS - Baixe o aplicativo aqui (v$BITRISE_BUILD_NUMBER): $BITRISE_PUBLIC_INSTALL_PAGE_URL
-            .'
+        - command: install
+    - npm@0.9.1:
+        inputs:
+        - command: run bundle:android
+  release_ios:
+    steps:
+    - set-xcode-build-number@1.0.7:
+        inputs:
+        - build_short_version_string: "$BITRISE_BUILD_NUMBER"
+        - plist_path: ios/musicplayce/Info.plist
+    - fastlane@2.3.12:
+        inputs:
+        - lane: ios beta
+        - work_dir: "$IOS_PROJECT_LOCATION"
+    - slack@2.7.3:
+        inputs:
+        - channel: "#musicplayce-bitrise"
+        - webhook_url: https://hooks.slack.com/services/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
+        - message: iOS - Baixe o aplicativo aqui (v$BITRISE_BUILD_NUMBER)
         - message_on_error: iOS - Erro
         - title_link: "$BITRISE_PUBLIC_INSTALL_PAGE_URL"
         - fields: |-
@@ -97,12 +97,43 @@ workflows:
             View Build|${BITRISE_BUILD_URL}
             View Commit|https://gitlab.com/dev_squad/musicplayce-app/commit/$BITRISE_GIT_COMMIT
             Install Page|${BITRISE_PUBLIC_INSTALL_PAGE_URL}
-        - image_url: "$BITRISE_PUBLIC_INSTALL_PAGE_QR_CODE_IMAGE_URL"
+    before_run:
+    - primary
 app:
   envs:
   - opts:
       is_expand: false
-    BITRISE_APK_PATH: android.apk
+    PROJECT_LOCATION: android
   - opts:
       is_expand: false
-    BITRISE_IPA_PATH: iOS.ipa
+    GRADLEW_PATH: android/gradlew
+  - opts:
+      is_expand: false
+    MODULE: app
+  - opts:
+      is_expand: false
+    BUILD_VARIANT: Debug
+  - opts:
+      is_expand: false
+    BITRISE_PROJECT_PATH: ios/musicplayce.xcodeproj
+  - opts:
+      is_expand: false
+    BITRISE_SCHEME: musicplayce
+  - opts:
+      is_expand: false
+    BITRISE_EXPORT_METHOD: development
+  - opts:
+      is_expand: false
+    IOS_PROJECT_LOCATION: ios
+  - opts:
+      is_expand: false
+    MATCH_USERNAME: apple@devsquad.email
+  - opts:
+      is_expand: false
+    MATCH_READONLY: 'true'
+  - opts:
+      is_expand: false
+    PILOT_USERNAME: apple@devsquad.email
+  - opts:
+      is_expand: false
+    PILOT_SKIP_WAITING_FOR_BUILD_PROCESSING: 'true'
